* ox-ioslide.el
*Export org-mode to Google I/O HTML5 slide..*
* Installation (not done yet)

If you have `melpa` and `emacs24` installed, simply type:

: M-x package-install org-ioslide

In your .emacs

#+BEGIN_SRC lisp
(require 'ox-ioslide)
#+END_SRC

* Development Info
** Editing CSS

[[http://compass-style.org/install/][Compass]] is a CSS preprocessor used to compile
SCSS/SASS into CSS. We chose SCSS for the new slide deck for maintainability,
easier browser compatibility, and because...it's the future!

That said, if not comfortable working with SCSS or don't want to learn something
new, not a problem. The generated .css files can already be found in
(see [[theme/css)][/theme/css]] You can just edit those and bypass SCSS altogether.
However, our recommendation is to use Compass. It's super easy to install and use.
	
*** Installing Compass and making changes

First, install compass:

: sudo gem update --system
: sudo gem install compass

Next, you'll want to watch for changes to the exiting .scss files in [[theme/scss][/theme/scss]]
and any new one you add:

: $ cd io-2012-slides
: $ compass watch

This command automatically recompiles the .scss file when you make a change.
Its corresponding .css file is output to [[theme/css][/theme/css]]. Slick.

By default, [[config.rb][config.rb]] in the main project folder outputs minified
.css. It's a best practice after all! However, if you want unminified files,
run watch with the style output flag:

    compass watch -s expanded

*Note:* You should not need to edit [[theme/scss/_base.scss][_base.scss]].
** Function Documentation


*** (org-ioslide-get-hlevel INFO)

Get HLevel value safely.
If option "HTML5SLIDE_HLEVEL" is set, retrieve integer value from it,
else get value from custom variable org-ioslide-hlevel.

*** (org-ioslide-center-block CENTER-BLOCK CONTENTS INFO)

Transcode a CENTER-BLOCK element from Org to HTML.
CONTENTS holds the contents of the block.  INFO is a plist
holding contextual information.

*** (org-ioslide-stylesheets INFO)

Return the HTML contents for declaring ioslide stylesheets.

*** (org-ioslide-export-block EXPORT-BLOCK CONTENTS INFO)

Transocde a EXPORT-BLOCK element from Org to ioslide.
CONTENTS is nil. NFO is a plist holding contextual information.

*** (org-ioslide-src-block SRC-BLOCK CONTENTS INFO)

Transcode a SRC-BLOCK element from Org to HTML.
If *+USE_PRETTIFY is true use org-ioslide--src-block to render the code block.
Else use org-html-src-block to convert source block to html.

*** (org-ioslide-headline HEADLINE CONTENTS INFO)

Transcode a HEADLINE element from Org to html5presentation.
CONTENTS holds the contents of the headline. INFO is a plist
holding contextual information.

*** (org-ioslide-section SECTION CONTENTS INFO)

Transcode a SECTION element from Org to HTML.
CONTENTS holds the contents of the section. INFO is a plist
holding contextual information.

*** (org-ioslide-template CONTENTS INFO)

Return complete document string after HTML conversion.
contents is the transoded contents string.
info is a plist holding eport options.

*** (org-ioslide-download-resource)

Download extra resource like css or js file to use this slide offline.

<!-- Error: (void-function &optional) -->

<!-- Error: (void-function &optional) -->

-----
<div style="padding-top:15px;color: *d0d0d0;">
Markdown README file generated by
<a href="https://github.com/mgalgs/make-readme-markdown">make-readme-markdown.el</a>
</div>
